// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txwuwnaaiixmnweaulak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4d3V3bmFhaWl4bW53ZWF1bGFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTk0MzcsImV4cCI6MjA2MDE5NTQzN30.yLimb9TEO8HzzktUF-xJSSaalKQUXJ5ZeGt9WqPUPqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);